### ISSUE TITLE
Issues using `PATCH` method

### ISSUE THREAD

**Issue by xentek** [postrank-labs/goliath#157]
The `PATCH` method was recently added via #148, which is fantastic. However, I don't think that's fully working yet. I get empty responses from the server when I try to route this method to my API classes.

Output from `CURL -x PATCH -v http://localhost:9000/example -d 'data={"example":true}'`:

``` bash
* About to connect() to localhost port 9000 (#0)
*   Trying 127.0.0.1... connected
* Connected to localhost (127.0.0.1) port 9000 (#0)
> PATCH /example HTTP/1.1
> User-Agent: curl/7.21.4 (universal-apple-darwin11.0) libcurl/7.21.4 OpenSSL/0.9.8r zlib/1.2.5
> Host: localhost:9000
> Accept: */*
> Content-Length: 59
> Content-Type: application/x-www-form-urlencoded
> 
* Empty reply from server
* Connection #0 to host localhost left intact
curl: (52) Empty reply from server
* Closing connection #0
```

I've changed the URL to `/example` in the output above, but the rest of the output is exactly what I get when I run this request against my server.

**Comment by dankozlowski** [comment]
This was merged a few years ago, and since no one is complaining I'm going to close this issue.  Thanks all!
