### ISSUE TITLE
Goliath::Rack::Validator not flexible

### ISSUE THREAD

**Issue by krukid** [postrank-labs/goliath#165]
The response format is hard-coded as `[status, headers, {:error => msg}]`.

Can we not use `[status, headers, msg]` instead?

I really need HTML responses when errors are raised.

**Comment by janko-m** [comment]
@igrigorik Is it possible to set default headers which will be returned even when `Goliath::Validation::Error` is raised?

**Comment by igrigorik** [comment]
@janko-m I assume https://github.com/postrank-labs/goliath/pull/327 is the answer? :)
