### ISSUE TITLE
1.0.5 release

### ISSUE THREAD

**Issue by Juanmcuello** [postrank-labs/goliath#325]
Hi, Is there any plan on releasing version 1.0.5?

**Comment by dankozlowski** [comment]
We'd like to use this in production (again).  Is there any movement here?

**Comment by igrigorik** [comment]
Apologies for holding up the train here.. :)

Yes, we can do a point release. That said, there are bunch of open pull requests and issues open -- any that we need to address / close out first? I'd appreciate someone jumping in to help / happy to add folks as collaborators.

**Comment by Juanmcuello** [comment]
It would be great to have a new release at least with the changes merged until now, as the last release was 3 years ago.

We can then continue reviewing open issues and pull requests.

**Comment by dankozlowski** [comment]
Agreed, the lack of support here is becoming a subject on contention when considering EM vs other C10K patterns in Ruby, like Celluloid.

**Comment by igrigorik** [comment]
@dankozlowski @Juanmcuello apologies about the delays. I'm happy to push a new release, and even better, give commit and rubygems access to anyone interested in working on it. Either of you interested? 

It looks like some specs are breaking due to outdated dependency.. I'd prefer to get that fixed before we push a new build?

**Comment by Juanmcuello** [comment]
@igrigorik , It would be great to give you and @dankozlowski a hand maintaining the project if you need it. Count on me.

Regarding the outdated dependencies, I created a PR (#330) that updates rspec, fixing the failed specs.

**Comment by igrigorik** [comment]
@Juanmcuello thanks for PR! Merged, still seeing some failures though.. left a comment on the PR.

Also, you should get an invite ... :)

**Comment by dankozlowski** [comment]
@igrigorik I'd love to help out!  100% in.  Also happy to help fix the build so we can get 1.5 out the door!

**Comment by igrigorik** [comment]
@dankozlowski awesome, check your invites! Thanks for jumping in.

**Comment by igrigorik** [comment]
I'm still struggling to figure out why current build is failing on my end.. but Travis is green. =|

Do you guys see any other issues or PRs we want to land before 1.0.5? If not, I can push new release on rubygems.

**Comment by Juanmcuello** [comment]
@igrigorik , I created another PR (#331) that removes a some warnings. 

I was skimming issues/PRs and, although there are some issues related to config files that I personally would like to address, I think it would take some effort to analyze them properly, so probably master is good enough as it is for releasing 1.0.5.

Anyway, it would be better if you can figure out why your tests are failing in your local box before doing the release, just in case we have missed anything.

**Comment by igrigorik** [comment]
Thanks for #331!

> I was skimming issues/PRs and, although there are some issues related to config files that I personally would like to address, I think it would take some effort to analyze them properly, so probably master is good enough as it is for releasing 1.0.5.

sgtm.

> Anyway, it would be better if you can figure out why your tests are failing in your local box before doing the release, just in case we have missed anything.

Still puzzled over this. That said, it does look like it's something wonky in my environment.

Pushed 1.0.5 to rubygems. Please give it a try and reopen if you stumble across any issues.

**Comment by Juanmcuello** [comment]
Excelent @igrigorik! I'll give it a try. Thanks!

**Comment by dankozlowski** [comment]
Woo!  In testing now.
