### ISSUE TITLE
Goliath JSON middleware incompatible with JSONAPI

### ISSUE THREAD

**Issue by dankozlowski** [postrank-labs/goliath#334]
Because the content-type for JSONAPI is `application/vnd.api+json`, the middleware does not identify the response as JSON.  Quick fix, just need to add `vnd.api+json` to the regex that `#json_response?` uses to determine the content type.

**Comment by igrigorik** [comment]
According to the [docs](http://jsonapi.org/format/#introduction), it should be `application/vnd.api+json`.

**Comment by dankozlowski** [comment]
@igrigorik Good, catch, thank you.  I've updated the original issue, and I'll have a PR for the fix ready shortly.
